# railway.toml
[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
# Database will be automatically provided by Railway
# Set these in Railway dashboard:
# API_TOKEN = "your-secure-api-token"
# LRS_ENDPOINT = "https://your-lrs.com/xapi"
# LRS_TOKEN = "your-lrs-token"
# WEBHOOK_ENDPOINT = "https://your-webhook.com"
# WEBHOOK_TOKEN = "your-webhook-token"
